site_name: Zel Ecosystem
dev_addr: 193.188.15.163:8888
repo_url: https://github.com/zelcash/zelwiki
repo_name: Zel Wiki
edit_uri: ""

theme:
  name: material
  features:
    -tabs
    -instant
  palette:
    scheme: slate
    primary: blue
    accent: indigo
  logo: img/Logos/logo.png
  favicon: img/Logos/logo.png
  features:
    - instant
    - tabs
  
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
      
plugins:
  - search
  
google_analytics:
  - UA-168637799-1
  - auto
  
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zelcash
    - icon: fontawesome/brands/medium
      link: https://medium.com/@ZelOfficial
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zelcash
    - icon: fontawesome/brands/twitter-square
      link: https://twitter.com/ZelCore
    - icon: fontawesome/brands/discord
      link: https://discord.io/zel
    - icon: fontawesome/brands/telegram-plane
      link: https://t.me/zelhub
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/ZelHub
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/ZelOfficial/
      
nav:
  - Home:
      - index.md
  - Zel:
      - Zel Ecosystem Overview: zel/zel.md
      - Zel Team: zel/zel_team.md
      - Zel Crypto Conference: zel/zel_con1.md
      - Zel Exchanges: zel/zel_exchanges.md
      - Roadmap: zel/zel_roadmap.md
      - Social Media Links: zel/zel_social.md
      - Installing Daemon: zel/zel_daemoninstall.md
  - ZelCore:
      - ZelCore Overview : zelcore/zelcore.md
      - ZelCore Supported Assets: zelcore/zelcore_assets.md
      - ZelCore Features: zelcore/zelcore_features.md
      - ZelCore+: zelcore/zelcore_+.md
  - ZelNodes:
      - Zel Computational Network Overview: zelnodes/zelnodes.md
      - Set Up ZelNode | RECOMMENDED: zelnodes/zelnode_setupfull.md
      - Set Up ZelNode | Alternate: zelnodes/zelnode_setupscript.md
      - Set up ZelNode | Manually: zelnodes/zelnode_setupmanual.md
      - ZelBench Commands: zelnodes/zelnode_benchcommands.md
  - Flux OS:
      - Flux Overview: flux/flux.md
      - Roadmap: flux/flux_roadmap.md
      - Flux API: flux/flux_api.md
      - Governance: flux/flux_gov.md
  - ZelID:
      - ZelID Overview: zelid/zelid.md
      - ZelID Modules:
        - d2FA Security Layer: zelid/zelid_d2fa.md
        - Easy Login: zelid/zelid_easylogin.md
        - Message Signing: zelid/zelid_signing.md
  - ZelLabs:
      - ZelLabs Overview: zellabs/zellabs.md
  - Zel Foundation:
      - Zel Foundation Overview: foundation/zelfoundation.md
      